In [6]:
import numpy as np

def get_input_matrix(rows, columns, matrix_num):
    matrix = []
    for i in range(rows):
        row = list(map(int, input(f"Enter row {i + 1} of matrix {matrix_num} (separate elements by space): ").split()))
        if len(row) != columns:
            print("Invalid number of elements in the row. Try again.")
            return None
        matrix.append(row)
    return np.array(matrix)

def matrix_addition(matrix1, matrix2):
    return np.add(matrix1, matrix2)

def matrix_subtraction(matrix1, matrix2):
    return np.subtract(matrix1, matrix2)

def scalar_matrix_multiplication(matrix, scalar):
    return np.multiply(matrix, scalar)

def elementwise_matrix_multiplication(matrix1, matrix2):
    return np.multiply(matrix1, matrix2)

def matrix_multiplication(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

def matrix_transpose(matrix):
    return np.transpose(matrix)

def trace_of_matrix(matrix):
    return np.trace(matrix)

def solve_linear_equations(matrix, vector):
    return np.linalg.solve(matrix, vector)

def matrix_determinant(matrix):
    return np.linalg.det(matrix)

def matrix_inverse(matrix):
    return np.linalg.inv(matrix)

def eigen_values_and_vectors(matrix):
    return np.linalg.eig(matrix)

def main():
    # Getting inputs from the user
    m1 = int(input("Enter the number of rows for Matrix 1: "))
    n1 = int(input("Enter the number of columns for Matrix 1: "))
    matrix1 = get_input_matrix(m1, n1, 1)

    m2 = int(input("Enter the number of rows for Matrix 2: "))
    n2 = int(input("Enter the number of columns for Matrix 2: "))
    matrix2 = get_input_matrix(m2, n2, 2)

    if matrix1 is None or matrix2 is None:
        print("Invalid input. Exiting...")
        return

    print("\nInputs:")
    print("Matrix 1:")
    print(matrix1)
    print("Matrix 2:")
    print(matrix2)

    # Menu driven function
    while True:
        print("\nMatrix Operations:")
        print("1. Matrix Addition")
        print("2. Matrix Subtraction")
        print("3. Scalar Matrix Multiplication")
        print("4. Elementwise Matrix Multiplication")
        print("5. Matrix Multiplication")
        print("6. Matrix Transpose")
        print("7. Trace of a Matrix")
        print("8. Solve System of Linear Equations")
        print("9. Determinant")
        print("10. Inverse")
        print("11. Eigen Value and Eigen Vector")
        print("12. Exit")
        choice = int(input("Enter your choice: "))

        if choice == 1:
            print("Matrix Addition:")
            result = matrix_addition(matrix1, matrix2)
            print(result)

        elif choice == 2:
            print("Matrix Subtraction:")
            result = matrix_subtraction(matrix1, matrix2)
            print(result)

        elif choice == 3:
            scalar = float(input("Enter the scalar value: "))
            print("Scalar Matrix Multiplication:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2\n"))
            if rot == 1:
                result = scalar_matrix_multiplication(matrix1, scalar)
            elif rot == 2:
                result = scalar_matrix_multiplication(matrix2, scalar)
            print(result)

        elif choice == 4:
            print("Elementwise Matrix Multiplication:")
            result = elementwise_matrix_multiplication(matrix1, matrix2)
            print(result)

        elif choice == 5:
            print("Matrix Multiplication:")
            result = matrix_multiplication(matrix1, matrix2)
            print(result)

        elif choice == 6:
            print("Matrix Transpose:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
            if rot == 1:
                result = matrix_transpose(matrix1)
            elif rot == 2:
                result = matrix_transpose(matrix2)
            print(result)

        elif choice == 7:
            print("Trace of a Matrix:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
            if rot == 1:
                result = trace_of_matrix(matrix1)
            elif rot == 2:
                result = trace_of_matrix(matrix2)
            print(result)

        elif choice == 8:
            vector_size = m1  # Use the number of rows in Matrix 1 as vector size
            vector = np.array(list(map(float, input(f"Enter the vector of size {vector_size} (separate elements by space): ").split())))
            if len(vector) != vector_size:
                print("Invalid vector length!")
            else:
                rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
                if rot == 1:
                    result = solve_linear_equations(matrix1, vector)
                elif rot == 2:
                    result = solve_linear_equations(matrix2, vector)
                print(result)

        elif choice == 9:
            print("Determinant:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
            if rot == 1:
                result = matrix_determinant(matrix1)
            elif rot == 2:
                result = matrix_determinant(matrix2)
            print(result)

        elif choice == 10:
            print("Inverse:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
            if rot == 1:
                result1 = matrix_determinant(matrix1)
                if result1 != 0:
                    result = matrix_inverse(matrix1)
                else:
                    print("No inverse for this matrix")
            elif rot == 2:
                result1 = matrix_determinant(matrix2)
                if result1 != 0:
                    result = matrix_inverse(matrix2)
                else:
                    print("No inverse for this matrix")
            print(result)

        elif choice == 11:
            print("Eigen Value and Eigen Vector:")
            rot = int(input("Choose the matrix \n 1. Matrix 1 \n 2. Matrix 2 \n"))
            if rot == 1:
                eigen_values, eigen_vectors = eigen_values_and_vectors(matrix1)
            elif rot == 2:
                eigen_values, eigen_vectors = eigen_values_and_vectors(matrix2)
            print("Eigen Values:")
            print(eigen_values)
            print("\nEigen Vectors:")
            print(eigen_vectors)

        elif choice == 12:
            print("Exiting...\n")
            break

        else:
            print("Invalid choice! Try again.")

if __name__ == "__main__":
    main()
12

Enter the number of rows for Matrix 1: 2
Enter the number of columns for Matrix 1: 2
Enter row 1 of matrix 1 (separate elements by space): 12 10
Enter row 2 of matrix 1 (separate elements by space): 11 10
Enter the number of rows for Matrix 2: 2
Enter the number of columns for Matrix 2: 2
Enter row 1 of matrix 2 (separate elements by space): 12 10
Enter row 2 of matrix 2 (separate elements by space): 23 76

Inputs:
Matrix 1:
[[12 10]
 [11 10]]
Matrix 2:
[[12 10]
 [23 76]]

Matrix Operations:
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Multiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve System of Linear Equations
9. Determinant
10. Inverse
11. Eigen Value and Eigen Vector
12. Exit
Enter your choice: 1
Matrix Addition:
[[24 20]
 [34 86]]

Matrix Operations:
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Multiplication
5. Matrix Multiplication
6. Matrix 

In [4]:
import pandas as pd

def find(acc_number):
    x = df['Account Number'].index
    sum = 0
    r = 0
    for i in x:
        if df['Account Number'][i] == acc_number:
            r = 1
        else:
            sum += 1
    if sum == len(x):
        r = -1
    return r

# Existing DataFrame from previous code
nme = ["Ram", "Sam", "Prabhu"]
ac_no = [9893893891, 9893893898, 9893893871]
ac_type = ["SB", "CA", "Sb"]
aadhar_no = [959389389173, 959389389179, 959389389159]
balance = [8989839, 7690990, 989330]
dict = {'Name': nme, 'Account Number': ac_no, 'Account Type': ac_type, 'Aadhar_No': aadhar_no, 'Balance': balance}
df = pd.DataFrame(dict)

# Save the DataFrame to CSV
df.to_csv("SBIAccountHolder.csv", index=False)

choice = 0
while choice != 6:
    print("\nAccount Options\n")
    print("1. Append Record\n")
    print("2. Delete Record\n")
    print("3. Credit amount\n")
    print("4. Debit amount\n")
    print("5. Account Details\n")
    print("6. Exit\n")
    choice = int(input("Enter the choice : "))

    if choice == 1:
        print("Adding Record\n")
        s = df.columns
        lis = []
        for i in range(len(s)):
            str1 = "Enter the {} of new Holder\n".format(s[i])
            if s[i] == 'Account Number' or s[i] == 'Balance':
                x = int(input(str1))
            else:
                x = input(str1)
            lis.append(x)
        lis1 = []
        lis1.append(lis)
        df1 = pd.DataFrame(lis1, columns=['Name', 'Account Number', 'Account Type', 'Aadhar_No', 'Balance'])
        df = pd.concat([df, df1], ignore_index=True)  # Using concat instead of append
        print("\nAdded Successfully")
    elif choice == 2:
        print("Deleting Record\n")
        acc_number = int(input("Enter the account number\n"))
        x1 = df.shape[0]
        condition = df['Account Number'] == acc_number
        df = df.drop(index=df[condition].index)
        x2 = df.shape[0]
        if x1 == x2:
            print("Enter a valid account number\n")
        else:
            print("\nDeleted Successfully")
    elif choice == 3:
        acc_number = int(input("Enter the account number\n"))
        fi = find(acc_number)
        if fi > 0:
            condition = df['Account Number'] == acc_number
            i1 = df[condition].index
            credit_amount = int(input("Enter the amount to be credited\n"))
            tr = df['Balance'][i1]
            tr += credit_amount
            df['Balance'][i1] = tr
            print("Amount Credited Successfully\n")
        else:
            print("Type a valid Account Number\n")
    elif choice == 4:
        acc_number = int(input("Enter the account number\n"))
        fi = find(acc_number)
        if fi > 0:
            condition = df['Account Number'] == acc_number
            i1 = df[condition].index
            debit_amount = int(input("Enter the amount to be debited\n"))
            tr = df['Balance'][i1]
            tr = int(tr)
            tr -= debit_amount
            if tr < 0:
                print("Error in debiting \n")
            else:
                df['Balance'][i1] = tr
                print("Amount Debited Successfully\n")
        else:
            print("Type a valid Account Number\n")
    elif choice == 5:
        acc_number = int(input("Enter the account number\n"))
        fi = find(acc_number)
        if fi > 0:
            condition = df['Account Number'] == acc_number
            i1 = df[condition].index
            print(df.iloc[i1])
        else:
            print("Type a valid Account Number\n")
    elif choice == 6:
        print('Exiting...\n')
        break
    else:
        print("Not a valid Input\n")
    print(df)
    df.to_csv('SBIAccountHolder.csv', index=False)



Account Options

1. Append Record

2. Delete Record

3. Credit amount

4. Debit amount

5. Account Details

6. Exit

Enter the choice : 1
Adding Record

Enter the Name of new Holder
jahan
Enter the Account Number of new Holder
1234
Enter the Account Type of new Holder
savingd
Enter the Aadhar_No of new Holder
123456
Enter the Balance of new Holder
2000

Added Successfully
     Name  Account Number Account Type     Aadhar_No  Balance
0     Ram      9893893891           SB  959389389173  8989839
1     Sam      9893893898           CA  959389389179  7690990
2  Prabhu      9893893871           Sb  959389389159   989330
3   jahan            1234      savingd        123456     2000

Account Options

1. Append Record

2. Delete Record

3. Credit amount

4. Debit amount

5. Account Details

6. Exit

Enter the choice : 3
Enter the account number
1234
Enter the amount to be credited
300


<ipython-input-4-9eeb4864b1ac>:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Balance'][i1] = tr


Amount Credited Successfully

     Name  Account Number Account Type     Aadhar_No  Balance
0     Ram      9893893891           SB  959389389173  8989839
1     Sam      9893893898           CA  959389389179  7690990
2  Prabhu      9893893871           Sb  959389389159   989330
3   jahan            1234      savingd        123456     2300

Account Options

1. Append Record

2. Delete Record

3. Credit amount

4. Debit amount

5. Account Details

6. Exit

Enter the choice : 4
Enter the account number
1234
Enter the amount to be debited
10


<ipython-input-4-9eeb4864b1ac>:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Balance'][i1] = tr


Amount Debited Successfully

     Name  Account Number Account Type     Aadhar_No  Balance
0     Ram      9893893891           SB  959389389173  8989839
1     Sam      9893893898           CA  959389389179  7690990
2  Prabhu      9893893871           Sb  959389389159   989330
3   jahan            1234      savingd        123456     2290

Account Options

1. Append Record

2. Delete Record

3. Credit amount

4. Debit amount

5. Account Details

6. Exit

Enter the choice : 4
Enter the account number
400000
Type a valid Account Number

     Name  Account Number Account Type     Aadhar_No  Balance
0     Ram      9893893891           SB  959389389173  8989839
1     Sam      9893893898           CA  959389389179  7690990
2  Prabhu      9893893871           Sb  959389389159   989330
3   jahan            1234      savingd        123456     2290

Account Options

1. Append Record

2. Delete Record

3. Credit amount

4. Debit amount

5. Account Details

6. Exit

Enter the choice : 4
Enter the ac